[shell]
program = "/bin/zsh"

[font.normal]
family = "MesloLGS NF"

[window]
dynamic_title = true
startup_mode = "Maximized"

[cursor.style]
shape = "Block"
blinking = "Always"

[selection]
save_to_clipboard = true

[scrolling]
history = 2000

