LC_COLLATE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"

alias python="python3"

export PATH="/usr/local/opt/sqlite/bin:$PATH"
export GPG_TTY=$(tty)
export PATH="/usr/local/sbin:$PATH"
